module.exports = {
  headers: {
    'Accept-Language': 'en-US,en;q=0.8',
    'Content-Type': 'application/json; charset=utf-8',
    Connection: 'keep-alive',
    Origin: 'https://developer.yodlee.com',
    Accept: 'application/json',
    Referer: 'https://developer.yodlee.com/apidocs/index.php'
  },
  options: {
    url: '',
    method: '',
    headers: '',
    form: '',
    json: ''
  },
  userSessionToken: '',
  cobSessionToken: '',
  token: '',
  post: 'POST',
  get: 'GET',
  put: 'PUT',
  cobrandLoginURL: 'cobrand/login',
  userLoginURL: 'user/login',
  userRegister: 'user/register',
  accessToken: 'user/accessTokens?appIds=10003600',
  accounts: 'accounts',
  container: 'bank/creditCard/investment/insurance/loan',
  redirectURL: '/account/callback&userId=111',
  appId: '10003600',
  fastlink: 'https://node.developer.yodlee.com/authenticate/restserver/',
  siteURL: 'providers',
  siteURLNEW: 'providers/providerAccounts?providerId=',
  sitesURL: 'providers/providerAccounts?providerAccountIds=',
  accountURL: 'accounts',
  investmentOptionsURL: 'accounts/investmentPlan/investmentOptions',
  investmentOptionsAssetClassificationURL: 'accounts/investmentPlan/investmentOptions?include=assetClassification',
  statementsURL: 'statements',
  transactionsURL: 'transactions',
  holdingsURL: 'holdings',
  holdingsAssetClassificationURL: 'holdings?include=assetClassification',
  holdingsAssetClassificationFilterURL: 'holdings?include=assetClassification&assetClassification.classificationType=COUNTRY&assetClassification.classificationValue<>US',
  portfolioSummaryURL: 'derived/networth',
  portfolioSummaryDetailsURL: 'derived/holdingSummary?include=details',
  refreshURLNEW: 'providers/providerAccounts/',
  refreshURL: 'refresh'
}  