module.exports = {
  db: 'DB ERROR!',
  exist: 'Email Duplicated!',
  mail: 'We can not send the email to you right now',
  unauth: 'Unauthorized',
  yodleeAuth: 'Yodlee Error',
  invalidEmail: 'Invalid Email',
  invalidName: 'Invalid Name. Name must be contain at least 3 characters or more',
  invalidPwd: 'Your password should contain a minimum of 8 characters, including at least 1 uppercase letter and 1 number',
  invalidPhone: 'Invalid Phone Number',
  invalidBirth: 'Invalid Date',
  inactive: 'Please activate your account before logging in.',
  dismatch: 'Invalid username or password',
  yodleeUser: 'Need to be registered in the yodlee',
  invalidURL: 'Not exist',
  badInput: 'Bad JSON',
  invalidYodleePwd: 'Password must be at least 8 characters long and contain at least one upper case letter, one number and any of these special characters !@#$%^&*() ',
  invalidGoalType: 'Invalid goal type. please select goal type',
  invalidGoalName: 'Invalid goal name. Goal name should include min 5 characters and max 30 characters',
  invalidGoalAmount: 'Invalid goal amount. Goal amount should be a number more than 1',
  existGoal: 'You have already created this goal',
  invalidUser: 'Invalid User',
  emptyGoal: 'You do not have any goal'
}